apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-demo-app
    labels:
      app: demo
spec:
 replicas: 3
 selector:
    matchLabels:
      app: demo
 template:
    metadata:
     name: my-demo-app
     labels: 
       app: demo
    spec:
     containers:
     - name: my-demo-whoami
       image: gcr.io/searce-msp-gcp/whoami-gcp:v1
       imagePullPolicy: Always
       ports:
       - containerPort: 8070
